// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/templates/CloudSpendActivityCalendar-Qjhl6V/App.tsx": () => import("../components/mockups/templates/CloudSpendActivityCalendar-Qjhl6V/App.tsx"),
  "./components/mockups/templates/KintsugiVoyageDepartureCalendar-19MWi5/App.tsx": () => import("../components/mockups/templates/KintsugiVoyageDepartureCalendar-19MWi5/App.tsx"),
  "./components/mockups/templates/MorningLabCommandCenter-ptskZZ/App.tsx": () => import("../components/mockups/templates/MorningLabCommandCenter-ptskZZ/App.tsx")
};
