import type { FormState } from '@/simulation-form-types';

export type SimulationRecipe = { id: string; label: string; description: string; patch: Partial<FormState> };

export const simulationRecipes: SimulationRecipe[] = [
  { id: 'payment-outage', label: 'Payment API outage / 503', description: 'Provider unavailable while charging a customer.', patch: { name: 'Payments · provider outage', failureType: 'http_503', statusCode: '503', responseBody: '{\n  "error": "service_unavailable",\n  "message": "payment provider unavailable"\n}', probability: '100', forwardRequest: false } },
  { id: 'rate-limit', label: 'Rate limited / 429', description: 'Exercise backoff and Retry-After handling.', patch: { name: 'Search · rate limited', failureType: 'http_429', statusCode: '429', responseBody: '{\n  "error": "rate_limited",\n  "retryAfter": 30\n}', probability: '100' } },
  { id: 'expired-auth', label: 'Expired authentication / 401', description: 'Force token refresh and sign-in recovery.', patch: { name: 'Auth · expired token', failureType: 'http_401', statusCode: '401', responseBody: '{\n  "error": "invalid_token",\n  "message": "access token expired"\n}', probability: '100' } },
  { id: 'slow-upstream', label: 'Slow upstream / latency', description: 'Add controlled latency without changing status.', patch: { name: 'Upstream · slow response', failureType: 'latency', statusCode: '200', latencyMs: '2500', probability: '100' } },
  { id: 'random-500', label: 'Random 500 errors', description: 'Inject intermittent internal errors.', patch: { name: 'API · random 500', failureType: 'http_500', statusCode: '500', probability: '25' } },
  { id: 'third-party-outage', label: 'Third-party API outage', description: 'Simulate a dependency returning a gateway error.', patch: { name: 'Third-party · outage', failureType: 'http_502', statusCode: '502', probability: '100', forwardRequest: false } },
  { id: 'network-failure', label: 'Network failure', description: 'Model a connection failure before a response exists.', patch: { name: 'Network · connection failure', failureType: 'connection_failure', statusCode: '', responseBody: '', probability: '100' } },
  { id: 'empty-response', label: 'Empty response', description: 'Return a successful transport with no body.', patch: { name: 'API · empty response', failureType: 'empty_response', statusCode: '200', responseBody: '', probability: '100' } },
  { id: 'malformed-json', label: 'Malformed JSON', description: 'Return an invalid payload to test parsing failures.', patch: { name: 'API · malformed JSON', failureType: 'malformed_json', statusCode: '200', responseBody: '{\n  "data": ', probability: '100' } },
  { id: 'intermittent-503', label: 'Intermittent 503', description: 'Exercise retry behavior under partial availability.', patch: { name: 'API · intermittent 503', failureType: 'http_503', statusCode: '503', probability: '35' } },
  { id: 'timeout', label: 'Timeout', description: 'Hold the request until the client timeout path fires.', patch: { name: 'Upstream · timeout', failureType: 'timeout', statusCode: '', responseBody: '', timeoutMs: '10000', probability: '100' } },
];

export function SimulationRecipes({ onSelect }: { onSelect: (patch: Partial<FormState>) => void }) {
  return <div className="mb-6 rounded-xl border border-border bg-card p-5 shadow-sm"><div className="mb-3"><h2 className="text-sm font-semibold">Start from a recipe</h2><p className="mt-1 text-xs text-muted-foreground">Prefill the existing form with a common failure scenario. You can change every value before saving.</p></div><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3"><select aria-label="Choose a simulation recipe" defaultValue="" onChange={event => { const recipe = simulationRecipes.find(item => item.id === event.target.value); if (recipe) onSelect(recipe.patch); event.currentTarget.value = ''; }} className="rounded-md border border-border bg-background px-3 py-2.5 text-xs sm:col-span-2 lg:col-span-1"><option value="">Choose a recipe…</option>{simulationRecipes.map(recipe => <option key={recipe.id} value={recipe.id}>{recipe.label}</option>)}</select>{simulationRecipes.slice(0, 2).map(recipe => <button key={recipe.id} type="button" onClick={() => onSelect(recipe.patch)} className="rounded-md border border-border bg-background px-3 py-2 text-left text-xs hover:border-primary/50 hover:bg-secondary"><span className="font-semibold">{recipe.label}</span><span className="mt-1 block text-muted-foreground">{recipe.description}</span></button>)}</div></div>;
}
