import { useEffect, useState } from 'react';
import { LogOut, Users, Clock3 } from 'lucide-react';
import { supabase } from '@/lib/supabase';

function dateLabel(value: string) { return new Intl.DateTimeFormat('en', { dateStyle: 'medium' }).format(new Date(value)); }

export default function SettingsPage() {
  const [workspace, setWorkspace] = useState<any>(null);
  const [weeks, setWeeks] = useState(2);
  const [teamId, setTeamId] = useState<number | null>(null);
  const [teamName, setTeamName] = useState('');
  const [teamCode, setTeamCode] = useState('');
  const [joinCode, setJoinCode] = useState('');
  const [message, setMessage] = useState('');
  const load = async () => { const response = await fetch('/api/workspace'); if (response.ok) { const data = await response.json(); setWorkspace(data); setWeeks(data.retentionWeeks); setTeamId(data.teams?.[0]?.id ?? null); } };
  useEffect(() => { void load(); }, []);
  const saveRetention = async () => { const response = await fetch('/api/workspace/retention', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ weeks, teamId }) }); setMessage(response.ok ? 'Retention policy saved.' : (await response.json()).error); await load(); };
  const createTeam = async () => { const response = await fetch('/api/teams', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name: teamName, code: teamCode }) }); setMessage(response.ok ? 'Team created.' : (await response.json()).error); setTeamName(''); setTeamCode(''); await load(); };
  const joinTeam = async () => { const response = await fetch('/api/teams/join', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ code: joinCode }) }); setMessage(response.ok ? 'Joined team.' : (await response.json()).error); setJoinCode(''); await load(); };
  const currentTeam = workspace?.teams?.find((team: any) => team.id === teamId);
  return <div className="space-y-6"><div><p className="eyebrow text-primary">Workspace</p><h1 className="page-title mt-2 text-[32px] font-bold">Settings</h1><p className="mt-2 text-sm text-muted-foreground">Manage your profile, workspace access, and data lifecycle.</p></div>
    {message && <div className="rounded-lg border border-primary/25 bg-primary/5 px-4 py-3 text-xs text-primary">{message}</div>}
    <section className="surface-panel rounded-xl border border-border bg-card p-5"><div className="flex items-center gap-2"><Users size={15} className="text-primary" /><h2 className="font-semibold">Profile</h2></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><div><p className="eyebrow text-muted-foreground">Name</p><p className="mt-1 text-sm">{workspace?.email?.split('@')[0] ?? '—'}</p></div><div><p className="eyebrow text-muted-foreground">Email</p><p className="mt-1 text-sm">{workspace?.email ?? '—'}</p></div></div><div className="mt-6 border-t border-border pt-5"><p className="eyebrow text-muted-foreground">Team / workspace</p><select value={teamId ?? ''} onChange={event => setTeamId(event.target.value ? Number(event.target.value) : null)} className="mt-2 w-full rounded-md border border-input bg-background px-3 py-2.5 text-sm"><option value="">Personal workspace</option>{workspace?.teams?.map((team: any) => <option value={team.id} key={team.id}>{team.name}</option>)}</select>{currentTeam && <p className="mt-2 text-xs text-muted-foreground">Team key: <span className="font-mono text-foreground">{currentTeam.teamCode}</span></p>}</div><div className="mt-6 grid gap-3 sm:grid-cols-3"><input value={teamName} onChange={event => setTeamName(event.target.value)} placeholder="New team name" className="rounded-md border border-input bg-background px-3 py-2 text-sm" /><input value={teamCode} onChange={event => setTeamCode(event.target.value)} placeholder="Team key (6+ chars)" className="rounded-md border border-input bg-background px-3 py-2 text-sm" /><button onClick={createTeam} className="rounded-md bg-primary px-3 py-2 text-xs font-semibold text-primary-foreground">Create team</button></div><div className="mt-3 flex gap-3"><input value={joinCode} onChange={event => setJoinCode(event.target.value)} placeholder="Existing team key" className="flex-1 rounded-md border border-input bg-background px-3 py-2 text-sm" /><button onClick={joinTeam} className="rounded-md border border-border px-3 py-2 text-xs font-semibold">Join team</button></div></section>
    <section className="surface-panel rounded-xl border border-border bg-card p-5"><div className="flex items-center gap-2"><Clock3 size={15} className="text-primary" /><h2 className="font-semibold">Data Retention</h2></div><p className="mt-2 text-sm text-muted-foreground">Personal data uses your policy. Shared team data uses the team owner&apos;s policy.</p><div className="mt-5 flex flex-wrap items-end gap-3"><label className="text-xs font-semibold">Policy<select value={weeks} onChange={event => setWeeks(Number(event.target.value))} className="mt-2 block rounded-md border border-input bg-background px-3 py-2.5 text-sm"><option value={1}>1 week</option><option value={2}>2 weeks</option></select></label><button onClick={saveRetention} className="rounded-md bg-primary px-4 py-2.5 text-xs font-semibold text-primary-foreground">Save policy</button></div><p className="mt-4 text-xs text-muted-foreground">Next deletion date: <span className="font-medium text-foreground">{dateLabel(new Date(Date.now() + weeks * 7 * 86400000).toISOString())}</span></p></section>
    <button onClick={() => void supabase?.auth.signOut()} className="inline-flex items-center gap-2 rounded-md border border-destructive/30 px-3.5 py-2.5 text-xs font-semibold text-destructive hover:bg-destructive/10"><LogOut size={14} /> Log out</button>
  </div>;
}
